# Generated by Django 4.2.6 on 2024-01-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0003_remove_userprofile_user_remove_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='purpose',
            field=models.CharField(max_length=120),
        ),
    ]
