# Generated by Django 4.2.6 on 2024-01-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('mail_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=20)),
                ('courses', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=20)),
                ('materials_provide', models.CharField(max_length=100)),
            ],
        ),
    ]
