# Generated by Django 4.2.6 on 2024-01-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_studentapplication_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
