# Generated by Django 4.2.6 on 2024-01-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_alter_studentapplication_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='mail_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
