# Generated by Django 4.2.6 on 2024-01-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0004_alter_studentapplication_mail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='materials_provide',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
