# Generated by Django 4.2.6 on 2024-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0005_alter_studentapplication_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
