# Generated by Django 4.2.6 on 2024-01-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0007_alter_studentapplication_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
